# Generated by Django 6.1.1 on 2026-09-23 20:07

import uuid

from django.db import migrations, models


def create_calendar_lock(apps, schema_editor):
    apps.get_model("core", "CalendarLock").objects.using(schema_editor.connection.alias).create(
        key=1
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarLock",
            fields=[
                (
                    "key",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
                ("version", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ClosedDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("start_at", models.DateTimeField(db_index=True)),
                ("end_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
            ],
        ),
        migrations.RunPython(create_calendar_lock, migrations.RunPython.noop),
    ]
